name: Build Apple Deck PDF
on:
  push:
    paths:
      - 'index.html'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm i puppeteer
      - run: node pdf.js
      - uses: actions/upload-artifact@v4
        with:
          name: 4thGround_Festival_Proposal_Apple
          path: deck.pdf
